ERROR - 2023-01-19 05:20:41 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:20:41 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:21:29 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:21:29 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:21:32 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:21:32 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:21:35 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:21:35 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:21:44 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:21:44 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:21:47 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:21:47 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:22:29 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:22:29 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:22:34 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:22:34 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:22:37 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:22:37 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:22:45 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:22:45 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:22:51 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:22:51 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:22:58 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:22:58 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:24:06 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:24:06 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:24:38 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:24:38 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:25:09 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:25:09 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
ERROR - 2023-01-19 05:25:12 --> Error connecting to the database: mysqli_sql_exception: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:171
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(171): mysqli->real_connect('127.0.0.1', 'test2', '1', 'rumah_kos', 3306, '', 0)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Connection refused in /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:215
Stack trace:
#0 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#5 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/public/index.php(67): CodeIgniter\CodeIgniter->run()
#12 /Applications/MAMP/htdocs/mbt_dev/jobworld/kosapp/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(47): require_once('/Applications/M...')
#13 {main}
CRITICAL - 2023-01-19 05:25:12 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
in SYSTEMPATH/Database/BaseConnection.php on line 418.
 1 SYSTEMPATH/Database/BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(624): CodeIgniter\Model->doFirst()
 5 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH/CodeIgniter.php(925): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH/CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 12:31:13 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 12:31:41 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 12:36:23 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 12:36:36 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 12:38:57 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 12:39:02 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 12:39:50 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 12:39:56 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 13:10:43 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 13:11:23 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 13:16:37 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 13:16:42 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 13:16:52 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 13:44:52 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 13:44:58 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getAll', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 13:46:41 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getOne', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 13:47:10 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getOne', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 13:53:41 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getOne', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 14:07:33 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getOne', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 14:07:36 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getOne', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 14:08:02 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getOne', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 14:13:01 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getOne', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 14:31:12 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getOne', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
CRITICAL - 2023-01-19 14:31:29 --> The action you requested is not allowed.
in SYSTEMPATH/Security/Security.php on line 307.
 1 SYSTEMPATH/Security/Security.php(307): CodeIgniter\Security\Exceptions\SecurityException::forDisallowedAction()
 2 SYSTEMPATH/Filters/CSRF.php(55): CodeIgniter\Security\Security->verify(Object(CodeIgniter\HTTP\IncomingRequest))
 3 SYSTEMPATH/Filters/Filters.php(173): CodeIgniter\Filters\CSRF->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH/CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('msUsers/getOne', 'before')
 5 SYSTEMPATH/CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
